# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=3)),
                ('gender', models.CharField(max_length=2)),
            ],
        ),
    ]
